//! The published BDEW codelist, as static data.
//!
//! Transcribed from EDI@Energy **"Codeliste der Lokationsbündelstrukturen"**,
//! version 1.0, published 31 March 2023 by BDEW, to be applied from
//! 1 October 2024 — chapters 3 and 4.
//!
//! Do not edit by hand: the check digits, the object-code cross-references and
//! the "every catalogued code is used by some structure" property are all
//! asserted by the tests in [`super`], and a stray edit fails them.

use super::{
    Flexibilitaet, Flussrichtung, Lokationsbuendelstruktur, Objektfunktion, Objektrolle, Objekttyp,
    StrukturObjekt,
};

/// Every object code the codelist defines, ordered by code.
///
/// Read through [`Objektrolle::from_code`](super::Objektrolle::from_code); the
/// slice itself is public so a caller can enumerate the catalogue.
pub static OBJEKTROLLEN: &[Objektrolle] = &[
    Objektrolle {
        code: "9992000001016",
        objekttyp: Objekttyp::Marktlokation,
        richtung: Some(Flussrichtung::Verbrauch),
        ebene: 1,
        funktion: None,
    },
    Objektrolle {
        code: "9992000001024",
        objekttyp: Objekttyp::TechnischeRessource,
        richtung: Some(Flussrichtung::Verbrauch),
        ebene: 1,
        funktion: None,
    },
    Objektrolle {
        code: "9992000001032",
        objekttyp: Objekttyp::Messlokation,
        richtung: Some(Flussrichtung::Verbrauch),
        ebene: 1,
        funktion: Some(Objektfunktion::Netzuebergabe),
    },
    Objektrolle {
        code: "9992000001058",
        objekttyp: Objekttyp::TechnischeRessource,
        richtung: Some(Flussrichtung::Erzeugung),
        ebene: 1,
        funktion: None,
    },
    Objektrolle {
        code: "9992000001066",
        objekttyp: Objekttyp::Marktlokation,
        richtung: Some(Flussrichtung::Erzeugung),
        ebene: 1,
        funktion: None,
    },
    Objektrolle {
        code: "9992000001074",
        objekttyp: Objekttyp::TechnischeRessource,
        richtung: Some(Flussrichtung::VerbrauchUndErzeugung),
        ebene: 1,
        funktion: Some(Objektfunktion::Speicher),
    },
    Objektrolle {
        code: "9992000001082",
        objekttyp: Objekttyp::Messlokation,
        richtung: Some(Flussrichtung::Verbrauch),
        ebene: 2,
        funktion: Some(Objektfunktion::Hinterschaltung),
    },
    Objektrolle {
        code: "9992000001090",
        objekttyp: Objekttyp::Messlokation,
        richtung: Some(Flussrichtung::Erzeugung),
        ebene: 2,
        funktion: Some(Objektfunktion::Hinterschaltung),
    },
    Objektrolle {
        code: "9992000001107",
        objekttyp: Objekttyp::Marktlokation,
        richtung: Some(Flussrichtung::Verbrauch),
        ebene: 2,
        funktion: None,
    },
    Objektrolle {
        code: "9992000001115",
        objekttyp: Objekttyp::Marktlokation,
        richtung: Some(Flussrichtung::Erzeugung),
        ebene: 2,
        funktion: None,
    },
    Objektrolle {
        code: "9992000001123",
        objekttyp: Objekttyp::Marktlokation,
        richtung: Some(Flussrichtung::Verbrauch),
        ebene: 3,
        funktion: None,
    },
    Objektrolle {
        code: "9992000001131",
        objekttyp: Objekttyp::Marktlokation,
        richtung: Some(Flussrichtung::Erzeugung),
        ebene: 3,
        funktion: None,
    },
    Objektrolle {
        code: "9992000001149",
        objekttyp: Objekttyp::TechnischeRessource,
        richtung: Some(Flussrichtung::Verbrauch),
        ebene: 2,
        funktion: None,
    },
    Objektrolle {
        code: "9992000001157",
        objekttyp: Objekttyp::TechnischeRessource,
        richtung: Some(Flussrichtung::Erzeugung),
        ebene: 2,
        funktion: None,
    },
    Objektrolle {
        code: "9992000001165",
        objekttyp: Objekttyp::TechnischeRessource,
        richtung: Some(Flussrichtung::VerbrauchUndErzeugung),
        ebene: 2,
        funktion: Some(Objektfunktion::Speicher),
    },
    Objektrolle {
        code: "9992000001181",
        objekttyp: Objekttyp::TechnischeRessource,
        richtung: Some(Flussrichtung::Erzeugung),
        ebene: 3,
        funktion: None,
    },
    Objektrolle {
        code: "9992000001206",
        objekttyp: Objekttyp::Messlokation,
        richtung: Some(Flussrichtung::Erzeugung),
        ebene: 3,
        funktion: Some(Objektfunktion::Hinterschaltung),
    },
    Objektrolle {
        code: "9992000001214",
        objekttyp: Objekttyp::Messlokation,
        richtung: Some(Flussrichtung::VerbrauchUndErzeugung),
        ebene: 1,
        funktion: Some(Objektfunktion::Netzuebergabe),
    },
    Objektrolle {
        code: "9992000001222",
        objekttyp: Objekttyp::Messlokation,
        richtung: Some(Flussrichtung::Verbrauch),
        ebene: 2,
        funktion: Some(Objektfunktion::Differenzmessung),
    },
    Objektrolle {
        code: "9992000001230",
        objekttyp: Objekttyp::Messlokation,
        richtung: Some(Flussrichtung::Erzeugung),
        ebene: 2,
        funktion: Some(Objektfunktion::Differenzmessung),
    },
    Objektrolle {
        code: "9992000001256",
        objekttyp: Objekttyp::Netzlokation,
        richtung: None,
        ebene: 1,
        funktion: None,
    },
    Objektrolle {
        code: "9992000001264",
        objekttyp: Objekttyp::TechnischeRessource,
        richtung: Some(Flussrichtung::VerbrauchUndErzeugung),
        ebene: 3,
        funktion: Some(Objektfunktion::Speicher),
    },
    Objektrolle {
        code: "9992000001272",
        objekttyp: Objekttyp::Marktlokation,
        richtung: Some(Flussrichtung::Verbrauch),
        ebene: 2,
        funktion: None,
    },
    Objektrolle {
        code: "9992000001280",
        objekttyp: Objekttyp::TechnischeRessource,
        richtung: Some(Flussrichtung::Verbrauch),
        ebene: 1,
        funktion: None,
    },
    Objektrolle {
        code: "9992000001298",
        objekttyp: Objekttyp::Marktlokation,
        richtung: Some(Flussrichtung::Erzeugung),
        ebene: 2,
        funktion: None,
    },
    Objektrolle {
        code: "9992000001305",
        objekttyp: Objekttyp::TechnischeRessource,
        richtung: Some(Flussrichtung::Erzeugung),
        ebene: 2,
        funktion: None,
    },
    Objektrolle {
        code: "9992000001313",
        objekttyp: Objekttyp::TechnischeRessource,
        richtung: Some(Flussrichtung::VerbrauchUndErzeugung),
        ebene: 2,
        funktion: Some(Objektfunktion::Speicher),
    },
];

/// Every Lokationsbündelstruktur the codelist defines, ordered by code.
///
/// Read through [`Lokationsbuendelstruktur::from_code`](super::Lokationsbuendelstruktur::from_code).
pub static STRUKTUREN: &[Lokationsbuendelstruktur] = &[
    Lokationsbuendelstruktur {
        code: "9992000000018",
        bezeichnung: "Verbrauch ohne Messlokation (Pauschal)",
        objekte: &[
            StrukturObjekt {
                code: "9992000001024",
                flexibilitaet: Flexibilitaet::Flexibel,
                min: 0,
                max: None,
                referenz_messlokation: &[],
                referenz_netzlokation: &[],
            },
            StrukturObjekt {
                code: "9992000001016",
                flexibilitaet: Flexibilitaet::Starr,
                min: 1,
                max: Some(1),
                referenz_messlokation: &[],
                referenz_netzlokation: &[],
            },
            StrukturObjekt {
                code: "9992000001256",
                flexibilitaet: Flexibilitaet::Flexibel,
                min: 0,
                max: None,
                referenz_messlokation: &[],
                referenz_netzlokation: &[],
            },
        ],
    },
    Lokationsbuendelstruktur {
        code: "9992000000026",
        bezeichnung: "Verbrauch mit einer Messlokation (Standard)",
        objekte: &[
            StrukturObjekt {
                code: "9992000001032",
                flexibilitaet: Flexibilitaet::Starr,
                min: 1,
                max: Some(1),
                referenz_messlokation: &[],
                referenz_netzlokation: &[],
            },
            StrukturObjekt {
                code: "9992000001024",
                flexibilitaet: Flexibilitaet::Flexibel,
                min: 0,
                max: None,
                referenz_messlokation: &[],
                referenz_netzlokation: &[],
            },
            StrukturObjekt {
                code: "9992000001016",
                flexibilitaet: Flexibilitaet::Starr,
                min: 1,
                max: Some(1),
                referenz_messlokation: &[],
                referenz_netzlokation: &[],
            },
            StrukturObjekt {
                code: "9992000001256",
                flexibilitaet: Flexibilitaet::Flexibel,
                min: 0,
                max: Some(1),
                referenz_messlokation: &[],
                referenz_netzlokation: &[],
            },
        ],
    },
    Lokationsbuendelstruktur {
        code: "9992000000034",
        bezeichnung: "Erzeugung mit einer Messlokation",
        objekte: &[
            StrukturObjekt {
                code: "9992000001214",
                flexibilitaet: Flexibilitaet::Starr,
                min: 1,
                max: Some(1),
                referenz_messlokation: &[],
                referenz_netzlokation: &[],
            },
            StrukturObjekt {
                code: "9992000001058",
                flexibilitaet: Flexibilitaet::Flexibel,
                min: 0,
                max: None,
                referenz_messlokation: &[],
                referenz_netzlokation: &[],
            },
            StrukturObjekt {
                code: "9992000001074",
                flexibilitaet: Flexibilitaet::Flexibel,
                min: 0,
                max: None,
                referenz_messlokation: &[],
                referenz_netzlokation: &[],
            },
            StrukturObjekt {
                code: "9992000001066",
                flexibilitaet: Flexibilitaet::Starr,
                min: 1,
                max: Some(1),
                referenz_messlokation: &[],
                referenz_netzlokation: &[],
            },
            StrukturObjekt {
                code: "9992000001016",
                flexibilitaet: Flexibilitaet::Flexibel,
                min: 0,
                max: Some(1),
                referenz_messlokation: &[],
                referenz_netzlokation: &[],
            },
            StrukturObjekt {
                code: "9992000001256",
                flexibilitaet: Flexibilitaet::Flexibel,
                min: 0,
                max: Some(1),
                referenz_messlokation: &[],
                referenz_netzlokation: &[],
            },
        ],
    },
    Lokationsbuendelstruktur {
        code: "9992000000042",
        bezeichnung: "Erzeugung ohne getrennt gemessene Erzeugung",
        objekte: &[
            StrukturObjekt {
                code: "9992000001214",
                flexibilitaet: Flexibilitaet::Starr,
                min: 1,
                max: Some(1),
                referenz_messlokation: &[],
                referenz_netzlokation: &[],
            },
            StrukturObjekt {
                code: "9992000001074",
                flexibilitaet: Flexibilitaet::Flexibel,
                min: 0,
                max: None,
                referenz_messlokation: &[],
                referenz_netzlokation: &[],
            },
            StrukturObjekt {
                code: "9992000001024",
                flexibilitaet: Flexibilitaet::Flexibel,
                min: 0,
                max: None,
                referenz_messlokation: &[],
                referenz_netzlokation: &[],
            },
            StrukturObjekt {
                code: "9992000001058",
                flexibilitaet: Flexibilitaet::Flexibel,
                min: 0,
                max: None,
                referenz_messlokation: &[],
                referenz_netzlokation: &[],
            },
            StrukturObjekt {
                code: "9992000001016",
                flexibilitaet: Flexibilitaet::Starr,
                min: 1,
                max: Some(1),
                referenz_messlokation: &[],
                referenz_netzlokation: &[],
            },
            StrukturObjekt {
                code: "9992000001066",
                flexibilitaet: Flexibilitaet::Starr,
                min: 1,
                max: Some(1),
                referenz_messlokation: &[],
                referenz_netzlokation: &[],
            },
            StrukturObjekt {
                code: "9992000001256",
                flexibilitaet: Flexibilitaet::Flexibel,
                min: 0,
                max: Some(1),
                referenz_messlokation: &[],
                referenz_netzlokation: &[],
            },
        ],
    },
    Lokationsbuendelstruktur {
        code: "9992000000068",
        bezeichnung: "Verbrauch mit flexibler Hinterschaltung ohne Erzeugung",
        objekte: &[
            StrukturObjekt {
                code: "9992000001032",
                flexibilitaet: Flexibilitaet::Starr,
                min: 1,
                max: Some(1),
                referenz_messlokation: &[],
                referenz_netzlokation: &[],
            },
            StrukturObjekt {
                code: "9992000001082",
                flexibilitaet: Flexibilitaet::Flexibel,
                min: 1,
                max: None,
                referenz_messlokation: &[],
                referenz_netzlokation: &[],
            },
            StrukturObjekt {
                code: "9992000001024",
                flexibilitaet: Flexibilitaet::Flexibel,
                min: 0,
                max: None,
                referenz_messlokation: &[],
                referenz_netzlokation: &[],
            },
            StrukturObjekt {
                code: "9992000001149",
                flexibilitaet: Flexibilitaet::Flexibel,
                min: 0,
                max: None,
                referenz_messlokation: &["9992000001082"],
                referenz_netzlokation: &[],
            },
            StrukturObjekt {
                code: "9992000001016",
                flexibilitaet: Flexibilitaet::Starr,
                min: 1,
                max: Some(1),
                referenz_messlokation: &[],
                referenz_netzlokation: &[],
            },
            StrukturObjekt {
                code: "9992000001107",
                flexibilitaet: Flexibilitaet::Flexibel,
                min: 1,
                max: None,
                referenz_messlokation: &["9992000001082"],
                referenz_netzlokation: &[],
            },
            StrukturObjekt {
                code: "9992000001256",
                flexibilitaet: Flexibilitaet::Flexibel,
                min: 0,
                max: Some(1),
                referenz_messlokation: &[],
                referenz_netzlokation: &[],
            },
        ],
    },
    Lokationsbuendelstruktur {
        code: "9992000000076",
        bezeichnung:
            "Verbrauch mit flexibler Hinterschaltung und nicht getrennt gemessener Erzeugung",
        objekte: &[
            StrukturObjekt {
                code: "9992000001214",
                flexibilitaet: Flexibilitaet::Starr,
                min: 1,
                max: Some(1),
                referenz_messlokation: &[],
                referenz_netzlokation: &[],
            },
            StrukturObjekt {
                code: "9992000001082",
                flexibilitaet: Flexibilitaet::Flexibel,
                min: 1,
                max: None,
                referenz_messlokation: &[],
                referenz_netzlokation: &[],
            },
            StrukturObjekt {
                code: "9992000001024",
                flexibilitaet: Flexibilitaet::Flexibel,
                min: 0,
                max: None,
                referenz_messlokation: &[],
                referenz_netzlokation: &[],
            },
            StrukturObjekt {
                code: "9992000001149",
                flexibilitaet: Flexibilitaet::Flexibel,
                min: 0,
                max: None,
                referenz_messlokation: &["9992000001082"],
                referenz_netzlokation: &[],
            },
            StrukturObjekt {
                code: "9992000001074",
                flexibilitaet: Flexibilitaet::Flexibel,
                min: 0,
                max: None,
                referenz_messlokation: &[],
                referenz_netzlokation: &[],
            },
            StrukturObjekt {
                code: "9992000001058",
                flexibilitaet: Flexibilitaet::Flexibel,
                min: 0,
                max: None,
                referenz_messlokation: &[],
                referenz_netzlokation: &[],
            },
            StrukturObjekt {
                code: "9992000001016",
                flexibilitaet: Flexibilitaet::Starr,
                min: 1,
                max: Some(1),
                referenz_messlokation: &[],
                referenz_netzlokation: &[],
            },
            StrukturObjekt {
                code: "9992000001107",
                flexibilitaet: Flexibilitaet::Flexibel,
                min: 1,
                max: None,
                referenz_messlokation: &["9992000001082"],
                referenz_netzlokation: &[],
            },
            StrukturObjekt {
                code: "9992000001066",
                flexibilitaet: Flexibilitaet::Starr,
                min: 1,
                max: Some(1),
                referenz_messlokation: &[],
                referenz_netzlokation: &[],
            },
            StrukturObjekt {
                code: "9992000001256",
                flexibilitaet: Flexibilitaet::Flexibel,
                min: 0,
                max: Some(1),
                referenz_messlokation: &[],
                referenz_netzlokation: &[],
            },
        ],
    },
    Lokationsbuendelstruktur {
        code: "9992000000084",
        bezeichnung:
            "Verbrauch mit flexibler Hinterschaltung und getrennt gemessener flexibler Erzeugung",
        objekte: &[
            StrukturObjekt {
                code: "9992000001214",
                flexibilitaet: Flexibilitaet::Starr,
                min: 1,
                max: Some(1),
                referenz_messlokation: &[],
                referenz_netzlokation: &[],
            },
            StrukturObjekt {
                code: "9992000001082",
                flexibilitaet: Flexibilitaet::Flexibel,
                min: 1,
                max: None,
                referenz_messlokation: &[],
                referenz_netzlokation: &[],
            },
            StrukturObjekt {
                code: "9992000001090",
                flexibilitaet: Flexibilitaet::Flexibel,
                min: 1,
                max: None,
                referenz_messlokation: &[],
                referenz_netzlokation: &[],
            },
            StrukturObjekt {
                code: "9992000001024",
                flexibilitaet: Flexibilitaet::Flexibel,
                min: 0,
                max: None,
                referenz_messlokation: &[],
                referenz_netzlokation: &[],
            },
            StrukturObjekt {
                code: "9992000001149",
                flexibilitaet: Flexibilitaet::Flexibel,
                min: 0,
                max: None,
                referenz_messlokation: &["9992000001082"],
                referenz_netzlokation: &[],
            },
            StrukturObjekt {
                code: "9992000001165",
                flexibilitaet: Flexibilitaet::Flexibel,
                min: 0,
                max: None,
                referenz_messlokation: &["9992000001090"],
                referenz_netzlokation: &[],
            },
            StrukturObjekt {
                code: "9992000001157",
                flexibilitaet: Flexibilitaet::Flexibel,
                min: 0,
                max: None,
                referenz_messlokation: &["9992000001090"],
                referenz_netzlokation: &[],
            },
            StrukturObjekt {
                code: "9992000001016",
                flexibilitaet: Flexibilitaet::Starr,
                min: 1,
                max: Some(1),
                referenz_messlokation: &[],
                referenz_netzlokation: &[],
            },
            StrukturObjekt {
                code: "9992000001107",
                flexibilitaet: Flexibilitaet::Flexibel,
                min: 1,
                max: None,
                referenz_messlokation: &["9992000001082"],
                referenz_netzlokation: &[],
            },
            StrukturObjekt {
                code: "9992000001272",
                flexibilitaet: Flexibilitaet::Flexibel,
                min: 0,
                max: None,
                referenz_messlokation: &["9992000001090"],
                referenz_netzlokation: &[],
            },
            StrukturObjekt {
                code: "9992000001115",
                flexibilitaet: Flexibilitaet::Flexibel,
                min: 1,
                max: None,
                referenz_messlokation: &["9992000001090"],
                referenz_netzlokation: &[],
            },
            StrukturObjekt {
                code: "9992000001256",
                flexibilitaet: Flexibilitaet::Flexibel,
                min: 0,
                max: Some(1),
                referenz_messlokation: &[],
                referenz_netzlokation: &[],
            },
        ],
    },
    Lokationsbuendelstruktur {
        code: "9992000000109",
        bezeichnung: "Summenmessung Verbrauch ohne Erzeugung",
        objekte: &[
            StrukturObjekt {
                code: "9992000001032",
                flexibilitaet: Flexibilitaet::Flexibel,
                min: 2,
                max: None,
                referenz_messlokation: &[],
                referenz_netzlokation: &["9992000001256"],
            },
            StrukturObjekt {
                code: "9992000001024",
                flexibilitaet: Flexibilitaet::Flexibel,
                min: 0,
                max: None,
                referenz_messlokation: &["9992000001032"],
                referenz_netzlokation: &[],
            },
            StrukturObjekt {
                code: "9992000001016",
                flexibilitaet: Flexibilitaet::Starr,
                min: 1,
                max: Some(1),
                referenz_messlokation: &["9992000001032"],
                referenz_netzlokation: &[],
            },
            StrukturObjekt {
                code: "9992000001256",
                flexibilitaet: Flexibilitaet::Flexibel,
                min: 0,
                max: None,
                referenz_messlokation: &[],
                referenz_netzlokation: &[],
            },
        ],
    },
    Lokationsbuendelstruktur {
        code: "9992000000117",
        bezeichnung: "Summenmessung mit mindestens einer ungemessenen Erzeugung",
        objekte: &[
            StrukturObjekt {
                code: "9992000001214",
                flexibilitaet: Flexibilitaet::Flexibel,
                min: 1,
                max: None,
                referenz_messlokation: &[],
                referenz_netzlokation: &["9992000001256"],
            },
            StrukturObjekt {
                code: "9992000001032",
                flexibilitaet: Flexibilitaet::Flexibel,
                min: 0,
                max: None,
                referenz_messlokation: &[],
                referenz_netzlokation: &["9992000001256"],
            },
            StrukturObjekt {
                code: "9992000001024",
                flexibilitaet: Flexibilitaet::Flexibel,
                min: 0,
                max: None,
                referenz_messlokation: &["9992000001032"],
                referenz_netzlokation: &[],
            },
            StrukturObjekt {
                code: "9992000001280",
                flexibilitaet: Flexibilitaet::Flexibel,
                min: 0,
                max: None,
                referenz_messlokation: &["9992000001214"],
                referenz_netzlokation: &[],
            },
            StrukturObjekt {
                code: "9992000001074",
                flexibilitaet: Flexibilitaet::Flexibel,
                min: 0,
                max: None,
                referenz_messlokation: &["9992000001214"],
                referenz_netzlokation: &[],
            },
            StrukturObjekt {
                code: "9992000001058",
                flexibilitaet: Flexibilitaet::Flexibel,
                min: 0,
                max: None,
                referenz_messlokation: &["9992000001214"],
                referenz_netzlokation: &[],
            },
            StrukturObjekt {
                code: "9992000001016",
                flexibilitaet: Flexibilitaet::Starr,
                min: 1,
                max: Some(1),
                referenz_messlokation: &["9992000001032", "9992000001214"],
                referenz_netzlokation: &[],
            },
            StrukturObjekt {
                code: "9992000001066",
                flexibilitaet: Flexibilitaet::Flexibel,
                min: 1,
                max: None,
                referenz_messlokation: &["9992000001214"],
                referenz_netzlokation: &[],
            },
            StrukturObjekt {
                code: "9992000001256",
                flexibilitaet: Flexibilitaet::Flexibel,
                min: 0,
                max: None,
                referenz_messlokation: &[],
                referenz_netzlokation: &[],
            },
        ],
    },
    Lokationsbuendelstruktur {
        code: "9992000000125",
        bezeichnung: "Summenmessung mit mindestens einer separat gemessenen Erzeugung",
        objekte: &[
            StrukturObjekt {
                code: "9992000001214",
                flexibilitaet: Flexibilitaet::Flexibel,
                min: 1,
                max: None,
                referenz_messlokation: &[],
                referenz_netzlokation: &["9992000001256"],
            },
            StrukturObjekt {
                code: "9992000001032",
                flexibilitaet: Flexibilitaet::Flexibel,
                min: 0,
                max: None,
                referenz_messlokation: &[],
                referenz_netzlokation: &["9992000001256"],
            },
            StrukturObjekt {
                code: "9992000001090",
                flexibilitaet: Flexibilitaet::Flexibel,
                min: 1,
                max: None,
                referenz_messlokation: &["9992000001214"],
                referenz_netzlokation: &[],
            },
            StrukturObjekt {
                code: "9992000001024",
                flexibilitaet: Flexibilitaet::Flexibel,
                min: 0,
                max: None,
                referenz_messlokation: &["9992000001032"],
                referenz_netzlokation: &[],
            },
            StrukturObjekt {
                code: "9992000001280",
                flexibilitaet: Flexibilitaet::Flexibel,
                min: 0,
                max: None,
                referenz_messlokation: &["9992000001214"],
                referenz_netzlokation: &[],
            },
            StrukturObjekt {
                code: "9992000001157",
                flexibilitaet: Flexibilitaet::Flexibel,
                min: 0,
                max: None,
                referenz_messlokation: &["9992000001090"],
                referenz_netzlokation: &[],
            },
            StrukturObjekt {
                code: "9992000001165",
                flexibilitaet: Flexibilitaet::Flexibel,
                min: 0,
                max: None,
                referenz_messlokation: &["9992000001090"],
                referenz_netzlokation: &[],
            },
            StrukturObjekt {
                code: "9992000001107",
                flexibilitaet: Flexibilitaet::Flexibel,
                min: 0,
                max: None,
                referenz_messlokation: &["9992000001090"],
                referenz_netzlokation: &[],
            },
            StrukturObjekt {
                code: "9992000001016",
                flexibilitaet: Flexibilitaet::Starr,
                min: 1,
                max: Some(1),
                referenz_messlokation: &["9992000001214", "9992000001032"],
                referenz_netzlokation: &[],
            },
            StrukturObjekt {
                code: "9992000001115",
                flexibilitaet: Flexibilitaet::Flexibel,
                min: 1,
                max: None,
                referenz_messlokation: &["9992000001090"],
                referenz_netzlokation: &[],
            },
            StrukturObjekt {
                code: "9992000001256",
                flexibilitaet: Flexibilitaet::Flexibel,
                min: 0,
                max: None,
                referenz_messlokation: &[],
                referenz_netzlokation: &[],
            },
        ],
    },
    Lokationsbuendelstruktur {
        code: "9992000000133",
        bezeichnung: "Erzeugung mit getrennt gemessener Erzeugung",
        objekte: &[
            StrukturObjekt {
                code: "9992000001214",
                flexibilitaet: Flexibilitaet::Starr,
                min: 1,
                max: Some(1),
                referenz_messlokation: &[],
                referenz_netzlokation: &[],
            },
            StrukturObjekt {
                code: "9992000001090",
                flexibilitaet: Flexibilitaet::Flexibel,
                min: 1,
                max: None,
                referenz_messlokation: &[],
                referenz_netzlokation: &[],
            },
            StrukturObjekt {
                code: "9992000001024",
                flexibilitaet: Flexibilitaet::Flexibel,
                min: 0,
                max: None,
                referenz_messlokation: &[],
                referenz_netzlokation: &[],
            },
            StrukturObjekt {
                code: "9992000001157",
                flexibilitaet: Flexibilitaet::Flexibel,
                min: 0,
                max: None,
                referenz_messlokation: &["9992000001090"],
                referenz_netzlokation: &[],
            },
            StrukturObjekt {
                code: "9992000001165",
                flexibilitaet: Flexibilitaet::Flexibel,
                min: 0,
                max: None,
                referenz_messlokation: &["9992000001090"],
                referenz_netzlokation: &[],
            },
            StrukturObjekt {
                code: "9992000001016",
                flexibilitaet: Flexibilitaet::Starr,
                min: 1,
                max: Some(1),
                referenz_messlokation: &[],
                referenz_netzlokation: &[],
            },
            StrukturObjekt {
                code: "9992000001115",
                flexibilitaet: Flexibilitaet::Flexibel,
                min: 1,
                max: None,
                referenz_messlokation: &["9992000001090"],
                referenz_netzlokation: &[],
            },
            StrukturObjekt {
                code: "9992000001107",
                flexibilitaet: Flexibilitaet::Flexibel,
                min: 0,
                max: None,
                referenz_messlokation: &["9992000001090"],
                referenz_netzlokation: &[],
            },
            StrukturObjekt {
                code: "9992000001256",
                flexibilitaet: Flexibilitaet::Flexibel,
                min: 0,
                max: Some(1),
                referenz_messlokation: &[],
                referenz_netzlokation: &[],
            },
        ],
    },
    Lokationsbuendelstruktur {
        code: "9992000000159",
        bezeichnung: "Erzeugungskaskade mit ungemessener Erzeugung",
        objekte: &[
            StrukturObjekt {
                code: "9992000001214",
                flexibilitaet: Flexibilitaet::Starr,
                min: 1,
                max: Some(1),
                referenz_messlokation: &[],
                referenz_netzlokation: &[],
            },
            StrukturObjekt {
                code: "9992000001230",
                flexibilitaet: Flexibilitaet::Starr,
                min: 1,
                max: Some(1),
                referenz_messlokation: &[],
                referenz_netzlokation: &[],
            },
            StrukturObjekt {
                code: "9992000001149",
                flexibilitaet: Flexibilitaet::Flexibel,
                min: 0,
                max: None,
                referenz_messlokation: &[],
                referenz_netzlokation: &[],
            },
            StrukturObjekt {
                code: "9992000001165",
                flexibilitaet: Flexibilitaet::Flexibel,
                min: 0,
                max: None,
                referenz_messlokation: &[],
                referenz_netzlokation: &[],
            },
            StrukturObjekt {
                code: "9992000001157",
                flexibilitaet: Flexibilitaet::Flexibel,
                min: 0,
                max: None,
                referenz_messlokation: &[],
                referenz_netzlokation: &[],
            },
            StrukturObjekt {
                code: "9992000001058",
                flexibilitaet: Flexibilitaet::Flexibel,
                min: 0,
                max: None,
                referenz_messlokation: &[],
                referenz_netzlokation: &[],
            },
            StrukturObjekt {
                code: "9992000001107",
                flexibilitaet: Flexibilitaet::Starr,
                min: 1,
                max: Some(1),
                referenz_messlokation: &[],
                referenz_netzlokation: &[],
            },
            StrukturObjekt {
                code: "9992000001115",
                flexibilitaet: Flexibilitaet::Starr,
                min: 1,
                max: Some(1),
                referenz_messlokation: &[],
                referenz_netzlokation: &[],
            },
            StrukturObjekt {
                code: "9992000001066",
                flexibilitaet: Flexibilitaet::Starr,
                min: 1,
                max: Some(1),
                referenz_messlokation: &[],
                referenz_netzlokation: &[],
            },
            StrukturObjekt {
                code: "9992000001256",
                flexibilitaet: Flexibilitaet::Flexibel,
                min: 0,
                max: Some(1),
                referenz_messlokation: &[],
                referenz_netzlokation: &[],
            },
        ],
    },
    Lokationsbuendelstruktur {
        code: "9992000000167",
        bezeichnung: "Erzeugungskaskade mit gemessener und ungemessener Erzeugung",
        objekte: &[
            StrukturObjekt {
                code: "9992000001214",
                flexibilitaet: Flexibilitaet::Starr,
                min: 1,
                max: Some(1),
                referenz_messlokation: &[],
                referenz_netzlokation: &[],
            },
            StrukturObjekt {
                code: "9992000001230",
                flexibilitaet: Flexibilitaet::Starr,
                min: 1,
                max: Some(1),
                referenz_messlokation: &[],
                referenz_netzlokation: &[],
            },
            StrukturObjekt {
                code: "9992000001090",
                flexibilitaet: Flexibilitaet::Flexibel,
                min: 1,
                max: None,
                referenz_messlokation: &[],
                referenz_netzlokation: &[],
            },
            StrukturObjekt {
                code: "9992000001149",
                flexibilitaet: Flexibilitaet::Flexibel,
                min: 0,
                max: None,
                referenz_messlokation: &[],
                referenz_netzlokation: &[],
            },
            StrukturObjekt {
                code: "9992000001165",
                flexibilitaet: Flexibilitaet::Flexibel,
                min: 0,
                max: None,
                referenz_messlokation: &[],
                referenz_netzlokation: &[],
            },
            StrukturObjekt {
                code: "9992000001157",
                flexibilitaet: Flexibilitaet::Flexibel,
                min: 0,
                max: None,
                referenz_messlokation: &[],
                referenz_netzlokation: &[],
            },
            StrukturObjekt {
                code: "9992000001107",
                flexibilitaet: Flexibilitaet::Starr,
                min: 1,
                max: Some(1),
                referenz_messlokation: &[],
                referenz_netzlokation: &[],
            },
            StrukturObjekt {
                code: "9992000001115",
                flexibilitaet: Flexibilitaet::Starr,
                min: 1,
                max: Some(1),
                referenz_messlokation: &[],
                referenz_netzlokation: &[],
            },
            StrukturObjekt {
                code: "9992000001256",
                flexibilitaet: Flexibilitaet::Flexibel,
                min: 0,
                max: Some(1),
                referenz_messlokation: &[],
                referenz_netzlokation: &[],
            },
            StrukturObjekt {
                code: "9992000001313",
                flexibilitaet: Flexibilitaet::Flexibel,
                min: 0,
                max: None,
                referenz_messlokation: &["9992000001090"],
                referenz_netzlokation: &[],
            },
            StrukturObjekt {
                code: "9992000001305",
                flexibilitaet: Flexibilitaet::Flexibel,
                min: 0,
                max: None,
                referenz_messlokation: &["9992000001090"],
                referenz_netzlokation: &[],
            },
            StrukturObjekt {
                code: "9992000001272",
                flexibilitaet: Flexibilitaet::Flexibel,
                min: 0,
                max: None,
                referenz_messlokation: &["9992000001090"],
                referenz_netzlokation: &[],
            },
            StrukturObjekt {
                code: "9992000001298",
                flexibilitaet: Flexibilitaet::Flexibel,
                min: 1,
                max: None,
                referenz_messlokation: &["9992000001090"],
                referenz_netzlokation: &[],
            },
        ],
    },
    Lokationsbuendelstruktur {
        code: "9992000000175",
        bezeichnung: "Verbrauchskaskade mit ungemessenen TR (Wärmepumpenkaskade)",
        objekte: &[
            StrukturObjekt {
                code: "9992000001214",
                flexibilitaet: Flexibilitaet::Starr,
                min: 1,
                max: Some(1),
                referenz_messlokation: &[],
                referenz_netzlokation: &[],
            },
            StrukturObjekt {
                code: "9992000001222",
                flexibilitaet: Flexibilitaet::Starr,
                min: 1,
                max: Some(1),
                referenz_messlokation: &[],
                referenz_netzlokation: &[],
            },
            StrukturObjekt {
                code: "9992000001024",
                flexibilitaet: Flexibilitaet::Flexibel,
                min: 0,
                max: None,
                referenz_messlokation: &[],
                referenz_netzlokation: &[],
            },
            StrukturObjekt {
                code: "9992000001149",
                flexibilitaet: Flexibilitaet::Flexibel,
                min: 0,
                max: None,
                referenz_messlokation: &[],
                referenz_netzlokation: &[],
            },
            StrukturObjekt {
                code: "9992000001165",
                flexibilitaet: Flexibilitaet::Flexibel,
                min: 0,
                max: None,
                referenz_messlokation: &[],
                referenz_netzlokation: &[],
            },
            StrukturObjekt {
                code: "9992000001157",
                flexibilitaet: Flexibilitaet::Flexibel,
                min: 0,
                max: None,
                referenz_messlokation: &[],
                referenz_netzlokation: &[],
            },
            StrukturObjekt {
                code: "9992000001016",
                flexibilitaet: Flexibilitaet::Starr,
                min: 1,
                max: Some(1),
                referenz_messlokation: &[],
                referenz_netzlokation: &[],
            },
            StrukturObjekt {
                code: "9992000001107",
                flexibilitaet: Flexibilitaet::Starr,
                min: 1,
                max: Some(1),
                referenz_messlokation: &[],
                referenz_netzlokation: &[],
            },
            StrukturObjekt {
                code: "9992000001115",
                flexibilitaet: Flexibilitaet::Starr,
                min: 1,
                max: Some(1),
                referenz_messlokation: &[],
                referenz_netzlokation: &[],
            },
            StrukturObjekt {
                code: "9992000001256",
                flexibilitaet: Flexibilitaet::Flexibel,
                min: 0,
                max: Some(1),
                referenz_messlokation: &[],
                referenz_netzlokation: &[],
            },
        ],
    },
    Lokationsbuendelstruktur {
        code: "9992000000183",
        bezeichnung: "Verbrauchskaskade mit ungemessenem Verbrauch und gemessener Erzeugung",
        objekte: &[
            StrukturObjekt {
                code: "9992000001214",
                flexibilitaet: Flexibilitaet::Starr,
                min: 1,
                max: Some(1),
                referenz_messlokation: &[],
                referenz_netzlokation: &[],
            },
            StrukturObjekt {
                code: "9992000001222",
                flexibilitaet: Flexibilitaet::Starr,
                min: 1,
                max: Some(1),
                referenz_messlokation: &[],
                referenz_netzlokation: &[],
            },
            StrukturObjekt {
                code: "9992000001206",
                flexibilitaet: Flexibilitaet::Starr,
                min: 1,
                max: Some(1),
                referenz_messlokation: &[],
                referenz_netzlokation: &[],
            },
            StrukturObjekt {
                code: "9992000001024",
                flexibilitaet: Flexibilitaet::Flexibel,
                min: 0,
                max: None,
                referenz_messlokation: &[],
                referenz_netzlokation: &[],
            },
            StrukturObjekt {
                code: "9992000001149",
                flexibilitaet: Flexibilitaet::Flexibel,
                min: 0,
                max: None,
                referenz_messlokation: &[],
                referenz_netzlokation: &[],
            },
            StrukturObjekt {
                code: "9992000001181",
                flexibilitaet: Flexibilitaet::Flexibel,
                min: 0,
                max: None,
                referenz_messlokation: &[],
                referenz_netzlokation: &[],
            },
            StrukturObjekt {
                code: "9992000001264",
                flexibilitaet: Flexibilitaet::Flexibel,
                min: 0,
                max: None,
                referenz_messlokation: &[],
                referenz_netzlokation: &[],
            },
            StrukturObjekt {
                code: "9992000001016",
                flexibilitaet: Flexibilitaet::Starr,
                min: 1,
                max: Some(1),
                referenz_messlokation: &[],
                referenz_netzlokation: &[],
            },
            StrukturObjekt {
                code: "9992000001107",
                flexibilitaet: Flexibilitaet::Starr,
                min: 1,
                max: Some(1),
                referenz_messlokation: &[],
                referenz_netzlokation: &[],
            },
            StrukturObjekt {
                code: "9992000001123",
                flexibilitaet: Flexibilitaet::Flexibel,
                min: 0,
                max: Some(1),
                referenz_messlokation: &[],
                referenz_netzlokation: &[],
            },
            StrukturObjekt {
                code: "9992000001131",
                flexibilitaet: Flexibilitaet::Starr,
                min: 1,
                max: Some(1),
                referenz_messlokation: &[],
                referenz_netzlokation: &[],
            },
            StrukturObjekt {
                code: "9992000001256",
                flexibilitaet: Flexibilitaet::Flexibel,
                min: 0,
                max: Some(1),
                referenz_messlokation: &[],
                referenz_netzlokation: &[],
            },
        ],
    },
];
